# Information site
site_name: Wiki iMot3k
site_url: https://wiki.imot3k.fr
site_author: Communauté Discord iMot3k

site_description: >-
  Un Wiki fait par la communauté Discord iMot3k.

# Repository
repo_name: Wiki iMot3k
repo_url: https://github.com/Discord-iMot3k/wiki

# Copyright
copyright: Copyright &copy; 2024 - 2024 Staff Discord iMot3k


theme:
  name: material
  custom_dir: overrides
  language: fr
  logo: 'global_assets/WikiMot3k.png'
  favicon: 'global_assets/favicon.ico'
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
  icon:
    edit: material/pencil 
    view: material/eye
    repo: material/code-block-parentheses
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Passer en mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: dark-orange
      toggle:
        icon: material/toggle-switch
        name: Passer en mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light-blue
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Passer en mode préférence système

plugins:
  - privacy
  - search
  - social:
      enabled: !ENV [CI, false]
  #- blog
  - tags:
      #tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
  # - offline
  - git-committers:
      repository: "Discord-iMot3k/wiki"
      branch: master
      enabled: !ENV [CI, false]
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - pymdownx.blocks.caption
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  

extra:
  generator: true
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.imot3k.fr
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@imot3k_

extra_css:
  - stylesheets/extra.css