name: Mkdocs Build And Deploy
on:
  push:
    branches:
      - master 
permissions:
  contents: write
jobs:
  deploy_on_github:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone Repository
        run: |
          git clone https://github.com/Discord-iMot3k/Wiki.git .
          git fetch --all
          git reset --hard origin/master
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force

  deploy_to_production:
    runs-on: ubuntu-latest
    needs: deploy_on_github
    steps:
      - name: Git Clone Repository
        run: |
          if git clone https://github.com/Discord-iMot3k/Wiki.git; then
            echo "✅ Clonage du dépôt réussi."
          else
            echo "❌ Échec du clonage du dépôt."
            exit 1
          fi

      - name: Set Environment Variables
        env:
          DISCORD_WEHBOOK_LOG: ${{ secrets.DISCORD_WEHBOOK_LOG }}
          OAUTH_ID: ${{ secrets.OAUTH_ID }}
          OAUTH_KEY: ${{ secrets.OAUTH_KEY }}
          SVCGITHUB_SSH_KEYS: ${{ secrets.SVCGITHUB_SSH_KEYS }}
          VM_IPV4: ${{ secrets.VM_IPV4 }}
          VM_IPV6: ${{ secrets.VM_IPV6 }}
        run: echo "Environment variables set."

      - name: Install Tailscale
        run: |
          if curl -fsSL https://tailscale.com/install.sh | sh; then
            echo "✅ Installation de Tailscale réussie."
          else
            echo "❌ Échec de l'installation de Tailscale."
            exit 1
          fi

      - name: Configure Tailscale
        run: |
          if sudo tailscale up --auth-key=${{ secrets.OAUTH_KEY }} --advertise-tags=tag:github; then
            echo "✅ Configuration de Tailscale réussie."
          else
            echo "❌ Échec de la configuration de Tailscale."
            exit 1
          fi

      - name: SSH and Deploy
        run: |
          SSH_KEY_PATH="/tmp/svcgithub_key"
          echo "${{ secrets.SVCGITHUB_SSH_KEYS }}" > "$SSH_KEY_PATH"
          chmod 600 "$SSH_KEY_PATH"

          SSH_TARGET=""
          if [ -n "${{ secrets.VM_IPV4 }}" ]; then
            SSH_TARGET="${{ secrets.VM_IPV4 }}"
          elif [ -n "${{ secrets.VM_IPV6 }}" ]; then
            SSH_TARGET="${{ secrets.VM_IPV6 }}"
          else
            echo "❌ Aucune adresse IP fournie pour la VM."
            exit 1
          fi

          function deploy {
            ssh -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no svc-github@"$SSH_TARGET" "sleep 60 && rm -rf /var/www/html/{*,.*} && git clone --branch gh-pages https://github.com/Discord-iMot3k/Wiki.git /var/www/html/. && sudo nginx -s reload"
          }

          if deploy; then
            echo "✅ Connexion SSH et déploiement du dépôt réussis."
          else
            echo "❌ Échec de la connexion SSH ou du déploiement du dépôt."
            exit 1
          fi
      
      - name: Logout from Tailscale
        run: |
          if sudo tailscale logout; then
            echo "✅ Déconnexion de Tailscale réussie."
          else
            echo "❌ Échec de la déconnexion de Tailscale."
            exit 1
          fi