name: Pull Request Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      run: |
        git clone https://github.com/${{ github.repository }}.git .
        git checkout ${{ github.event.pull_request.head.sha }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build with MkDocs
      run: mkdocs build

    - name: Upload to bashupload website
      run: |
        zip -r wikimot3k.zip ./site
        curl bashupload.com -T wikimot3k.zip
