name: Manual Sync Script Execution

on:
  workflow_dispatch:

jobs:
  run_sync_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        env:
          DISCORD_WEHBOOK_LOG: ${{ secrets.DISCORD_WEHBOOK_LOG }}
          OAUTH_ID: ${{ secrets.OAUTH_ID }}
          OAUTH_KEY: ${{ secrets.OAUTH_KEY }}
          SVCGITHUB_SSH_KEYS: ${{ secrets.SVCGITHUB_SSH_KEYS }}
          VM_IPV4: ${{ secrets.VM_IPV4 }}
          VM_IPV6: ${{ secrets.VM_IPV6 }}
        run: echo "Environment variables set."

      - name: Run Sync Script
        run: bash sync.sh
